name: docker-push
on:
  push:
    branches: [ 'main' ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ github.ref_name }}
        env:
          DOCKER_USERNAME: licenseplated
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: licenseplated/code
          DOCKER_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin &&
          docker buildx create --name builder --bootstrap --use &&
          docker buildx build . --platform linux/amd64,linux/arm64 --push --tag ${DOCKER_REPO}:${DOCKER_TAG} &&
          echo Done
